spring.application.name=plataforma-educativa
server.port=8080

# Configuracion Oracle Cloud
spring.datasource.url=jdbc:oracle:thin:@plataformaeducativa_tp?TNS_ADMIN=./src/main/resources/wallet
spring.datasource.username=ADMIN
spring.datasource.password=Oraclecloud123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

oracle.jdbc.fanEnabled=false